#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VTSClient.UI.DroidNative.Resource", IsApplication=true)]

namespace VTSClient.UI.DroidNative
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::VTSClient.UI.DroidNative.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::VTSClient.UI.DroidNative.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::VTSClient.UI.DroidNative.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::VTSClient.UI.DroidNative.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::VTSClient.UI.DroidNative.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::VTSClient.UI.DroidNative.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::VTSClient.UI.DroidNative.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::VTSClient.UI.DroidNative.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::VTSClient.UI.DroidNative.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxBind = global::VTSClient.UI.DroidNative.Resource.Attribute.MvxBind;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxDropDownItemTemplate = global::VTSClient.UI.DroidNative.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxGroupItemTemplate = global::VTSClient.UI.DroidNative.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxItemTemplate = global::VTSClient.UI.DroidNative.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxLang = global::VTSClient.UI.DroidNative.Resource.Attribute.MvxLang;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxSource = global::VTSClient.UI.DroidNative.Resource.Attribute.MvxSource;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxTemplate = global::VTSClient.UI.DroidNative.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Id.MvvmCrossTagId = global::VTSClient.UI.DroidNative.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Droid.FullFragging.Resource.Id.MvxBindingTagUnique = global::VTSClient.UI.DroidNative.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxBinding;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding_MvxBind = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding_MvxLang = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxControl = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxControl;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxControl_MvxTemplate = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxExpandableListView = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxImageView = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxImageView;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxImageView_MvxSource = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxListView;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView_MvxItemTemplate = global::VTSClient.UI.DroidNative.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::VTSClient.UI.DroidNative.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::VTSClient.UI.DroidNative.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_drawer_light = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int mainIcon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvvmCrossTagId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MvxBindingTagUnique = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int button = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int buttonLogon = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int content_frame = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int drawer_layout = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int frag1 = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int left_drawer = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AccountLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ApproverItemView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreatePageMain = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CreateRegularVacationView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CreateSickLeaveView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CreateVacationActivityView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int CreateVacationTabView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Item_menu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MenuFragmentView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int VacationDetailsView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int VacationItemView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int VacationsLayout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int drawer_close = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int drawer_open = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int menu_refresh = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
